### PR TITLE
fix: 🐛 make router.basename work in icestark context

### LINKED ISSUE #4234: 基于 icejs 的微应用 basename 设置失效
应用入口 icestark.type 设置为 child 后，router.basename 在应用独立时设置消失

### PR DESCRIPTION
**Pull request by maoxiaoke**
Closes #4234

### CODE REVIEW

File: packages/plugin-icestark/src/runtime.tsx [hunk 1]
```diff
@@ -27,7 +27,10 @@ const module = ({ appConfig, addDOMRender, buildConfig, setRenderRouter, modifyR
   }
   if (appType === 'child') {
     const { icestarkUMD } = buildConfig;
-    const history = createHistory({ type, basename: getBasename() });
+
+    const childBasename = isInIcestark ? getBasename() : basename;
```
Comment (ClarkXia) [inline packages/plugin-icestark/src/runtime.tsx:31]: isInIcestark 是个 function

**Review by ClarkXia — CHANGES_REQUESTED** [review]

**Review by ClarkXia — APPROVED** [review]

**Review by luhc228 — APPROVED** [review]
