### PR TITLE
fix: get route assets by route manifest

### LINKED ISSUE #6078: memory 路由开启 injectInitialEntry 失效
### Describe the bug

- 对于 src/pages/xx/index.tsx 的路由插件，在开启 injectInitialEntry 后无法正常注入 memory router 的初始路径
- 驼峰文件夹的场景下同样无法正常注入 initialEntry

image

### Expected behavior

不报 warning 信息，正常注入 initialEntry

### Actual behavior

_No response_

### Version of ice.js

3.1.3

### Content of build.json or ice.config.mts

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ClarkXia**
Close #6078

### CODE REVIEW

File: packages/ice/src/commands/build.ts [hunk 1]
```diff
@@ -156,20 +157,7 @@ const build = async (
   output.paths = [...outputPaths];
 
   if (routeType === 'memory' && userConfig?.routes?.injectInitialEntry) {
```
Comment (luhc228) [inline packages/ice/src/commands/build.ts:159]: userConfig.routes.injectInitialEntry 现在有文档吗？好像没找到

**Review by chenjun1011 — DISMISSED** [review]

File: packages/ice/src/commands/build.ts (hunk 1 above)
Comment (ClarkXia) [reply packages/ice/src/commands/build.ts:159]: 文档单独添加合并到 master

**Review by luhc228 — DISMISSED** [review]

**Review by luhc228 — APPROVED** [review]

**Review by chenjun1011 — APPROVED** [review]

**Review by luhc228 — APPROVED** [review]
