### PR TITLE
fix: duplicate css

### LINKED ISSUE #7136: Document Link 中的 CSS 没有去重
### Describe the bug

假设应用的 AssetsManifest 如下

```ts
{
  publicPath: '/',
  entries: {
    main: [
      'css/vendors.css',
      'js/vendors.js',
      'css/main.css',
      'js/main.js'
    ]
  },
  pages: {
    layout: [
      'css/vendors.css',
      'js/vendors.js',
      'css/p_layout.css',
      'js/p_layout.js'
    ],
    'home': [
      'css/vendors.css',
      'js/vendors.js',
    ],
  }
}
```
页面级的 css 过滤后的结果，如下

### Expected behavior

vendors.css 被去重
```ts
[
  '/css/vendors.css',
  '/css/main.css',
  '/css/p_layout.css',
  '/css/p_friendgamerecord-index.css'
]
```

### Actual behavior

vendors.css 没有去重
```ts
[
  '/css/vendors.css',
  '/css/main.css',
  '/css/vendors.css',
  '/css/p_layout.css',
  '/css/vendors.css',
  '/css/p_friendgamerecord-index.css'
]
```

### Version of ice.js

3

### Content of build.json or ice.config.mts

```TypeScript

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by chenjun1011**
fix: https://github.com/alibaba/ice/issues/7136

### CODE REVIEW

File: packages/runtime/src/Document.tsx [hunk 1]
```diff
@@ -81,7 +81,15 @@ export const Links: LinksType = (props: LinksProps) => {
   const routeLinks = getLinks(matches, loaderData);
   const pageAssets = getPageAssets(matches, assetsManifest);
   const entryAssets = getEntryAssets(assetsManifest);
-  const styles = entryAssets.concat(pageAssets).filter(path => path.indexOf('.css') > -1);
+  let styles = entryAssets.concat(pageAssets).filter(path => path.indexOf('.css') > -1);
+
+  // Unique styles for duplicate CSS files.
+  const cssSet = {};
```
Comment (XGHeaven) [inline packages/runtime/src/Document.tsx:87]: Array.from(new Set) 呢？

File: .changeset/dull-steaks-melt.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+'@ice/runtime': patch
+---
+
+fix duplicate css
```
Comment (XGHeaven) [inline .changeset/dull-steaks-melt.md:5]: `fix:` ?

**Review by XGHeaven — APPROVED** [review]

**Review by ClarkXia — APPROVED** [review]
