### PR TITLE
fix(runtime): when SSR client send extra useless requests (fix #6306)

### LINKED ISSUE #6306: SSR 编译数据产物和运行时代码逻辑不匹配
### Describe the bug

SSR 编译数据产物 __ICE_APP_CONTEXT__ 中的字段为 loaderData
前端代码中的逻辑为读取 routesData ，导致前端运行时会多发一次请求

详见截图
image

### Expected behavior

代码中读取字段一致，不要发额外的请求

### Actual behavior

代码中读取字段不一致，会发额外发一次请求

### Version of ice.js

@ice/runtime 1.2.2

### Content of build.json or ice.config.mts

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by malei0311**
detail: SSR compile time data field 'loaderData' not match runtime 'routesData'
Fix: https://github.com/alibaba/ice/issues/6306

### CODE REVIEW

**Comment by ClarkXia** [comment]
Please sign CLA

File: packages/runtime/src/dataLoader.ts [hunk 1]
```diff
@@ -169,12 +169,12 @@ const cache = new Map<string, CachedResult>();
...
   const context = (window as any).__ICE_APP_CONTEXT__ || {};
   const matchedIds = context.matchedIds || [];
-  const routesData = context.routesData || {};
+  const loaderData = context.loaderData || {};
   const { renderMode } = context;
 
   const ids = ['_app'].concat(matchedIds);
   ids.forEach(id => {
-    const dataFromSSR = routesData[id];
+    const dataFromSSR = loaderData[id];
```
Comment (ClarkXia) [inline packages/runtime/src/dataLoader.ts:177]: 应该是 loaderData[id]?.data 吧，这里只需要读取数据

Comment (malei0311) [reply packages/runtime/src/dataLoader.ts:177]: 对的，我改一下

**Review by ClarkXia — APPROVED** [review]

**Review by chenjun1011 — APPROVED** [review]
