### PR TITLE
fix: support transform plugin in speedup mode

### LINKED ISSUE #6610: Task config of transformPlugins did not work in speedup mode
### Describe the bug

Task config of transformPlugins did not work in speedup mode.

### Expected behavior

Task config of transformPlugins works properly in speedup mode.

### Actual behavior

_No response_

### Version of ice.js

3.3.5

### Content of build.json or ice.config.mts

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ClarkXia**
Fix #6610

### CODE REVIEW

**Review by chenjun1011 — APPROVED** [review]

File: packages/shared-config/src/getCompilerPlugins.ts [hunk 1]
```diff
@@ -85,13 +86,15 @@ function getCompilerPlugins(rootDir: string, config: Config, compiler: Compiler,
...
     }));
   }
-
-  return compiler === 'webpack'
-    // Plugins will be transformed as webpack loader, the execute order of webpack loader is reversed.
-    ? compilerPlugins
-        .reverse()
-        .map((plugin) => createUnplugin(() => getPluginTransform(plugin, transformOptions)).webpack()) as Config['plugins']
-    : compilerPlugins.map(plugin => getPluginTransform(plugin, transformOptions));
+  console.log('compiler', compiler);
```
Comment (luhc228) [inline packages/shared-config/src/getCompilerPlugins.ts:89]: log

Comment (ClarkXia) [reply packages/shared-config/src/getCompilerPlugins.ts]: fixed

**Review by luhc228 — APPROVED** [review]

**Review by chenjun1011 — APPROVED** [review]
